config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'todos#index'

  resources :todos

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :contents, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :email, presence: true 
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :resource, :resource_name, :devise_mapping
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :name, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :name, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :name, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.where(user_id: current_user)
    @todo = Todo.new
  end

  def create
    @todo = Todo.create(contents: params[:todo][:contents], user_id: current_user.id)
    redirect_to :root
  end 

  def new
    @todo = Todo.new
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(contents: params[:todo][:contents])
    redirect_to :root
  end

  def destroy
    if current_user
      todo = Todo.find(params[:id])
      todo.destroy
      redirect_to :root
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeTodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.name %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% elsif "http://localhost:3000/users/sign_in" %>
    <%--%>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/todos/edit.html.erb
Let's update your Task!
<%= form_for(@todo, url: todo_path(@todo), html: {method: "patch"}) do |f| %>
  <%= f.text_field :contents, id:'contents', size: "60x12" %>
  <%= f.submit "Done" %>
<% end %>

app/views/todos/index.html.erb
<h1>Welcome Awesome TODOs</h1>
<p>Your current list of todo is: </p>
<% @todos.each do |todo| %>
  <ul>
    <li>
    <%= todo.contents %>
    <%= link_to "Edit", [:edit, todo] %>
    <%= link_to "Delete", todo, method: :delete %>
    </li>
  </ul>
<% end %>
<br>
<%= form_for(@todo, url: todos_path(@todo), html: {method: "post"}) do |f| %>
  <%= f.text_field :contents, id: 'contents', size: "60x12" %>
  <%= f.submit "New Task" %>
<% end %>